### ISSUE TITLE
Encountering issue attempting to open Plone site

### ISSUE THREAD

**Issue by girlandhercode** [derekdavenport/vscode-plonefs#2]
### What I'm trying to do:
Open Plone site in VS Code.

### What happened:
All add-ons seem to reload (just going by the status bar reloading all of the info for addons each time I attempt to open a site), and the site folder appears in the Workspace with no entries below it. It is simply the root of the site and when clicking the triangle icon to expand the folders/files there is nothing there. The below errors are from VS Code dev tool's console.

The sites I've tried:
/research/integrity
/conflictofinterest

### What I expected:
The site to open and the files/folders be shown in the file tree in this workspace.

### Other probably not important details:
The site I opened previously had not been opened by this add-on for a couple of months at least. I am sure my UofL password has changed since then - if that matters.

I have multiple (two) VS Code windows open when attempting this, only one for working on a Plone site.

### These are the errors from the VS Code Dev Tools:

```bash
[Extension Host] Activating extension `derekdavenport.vscode-plonefs` failed:  unable to get local issuer certificate
  | _logMessageInConsole | @ | workbench.main.js:3855
-- | -- | -- | --
  | _logOrShowMessage | @ | workbench.main.js:3855
  | (anonymous) | @ | workbench.main.js:3205
  | (anonymous) | @ | workbench.main.js:34
  | n | @ | workbench.main.js:34
  | $onExtensionActivationError | @ | workbench.main.js:3205
  | _doInvokeHandler | @ | workbench.main.js:3252
  | _invokeHandler | @ | workbench.main.js:3252
  | _receiveRequest | @ | workbench.main.js:3251
  | _receiveOneMessage | @ | workbench.main.js:3249
  | _protocol.onMessage.e | @ | workbench.main.js:3248
  | fire | @ | workbench.main.js:77
  | a | @ | workbench.main.js:321
  | e | @ | workbench.main.js:321
  | fire | @ | workbench.main.js:77
  | _receiveMessage | @ | workbench.main.js:330
  | S._socketDisposables.push._socketReader.onMessage.e | @ | workbench.main.js:327
  | fire | @ | workbench.main.js:77
  | acceptChunk | @ | workbench.main.js:323
  | _register._socket.onData.e | @ | workbench.main.js:323
  | t | @ | workbench.main.js:332
  | emit | @ | events.js:182
  | addChunk | @ | _stream_readable.js:279
  | readableAddChunk | @ | _stream_readable.js:264
  | Readable.push | @ | _stream_readable.js:219
  | onread | @ | net.js:636

```

And:
```bash
[Extension Host] Here is the error stack:  RequestError: unable to get local issuer certificate
	at ClientRequest.module.exports.a.exports.o.once.e (/home/<myusername>/.vscode/extensions/derekdavenport.vscode-plonefs-0.4.6/out/extension.js:31:18836)
	at Object.onceWrapper (events.js:273:13)
	at ClientRequest.emit (events.js:187:15)
	at ClientRequest.module.exports.a.exports.a.emit.n (/home/<myusername>/.vscode/extensions/derekdavenport.vscode-plonefs-0.4.6/out/extension.js:151:25893)
	at TLSSocket.socketErrorListener (_http_client.js:382:9)
	at TLSSocket.emit (events.js:182:13)
	at emitErrorNT (internal/streams/destroy.js:82:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

I am running VS Code:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-51-generic

on Ubuntu 18.04.2 LTS bionic

**Comment by derekdavenport** [comment]
I previously manually patched and included UofL's security certificates because they were not bundled correctly. I believe UofL fixed this when they updated their security certificates earlier this year. At any rate I removed the old certificates from the extension, and things should be working now.
